"""Stable error-code taxonomy (docs/08 §3).

`code` is the machine-stable identifier; `type` URI is the docs namespace.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION = "VALIDATION.INVALID"
    AUTH_MISSING = "AUTH.TOKEN_MISSING"
    AUTH_INVALID = "AUTH.TOKEN_INVALID"
    AUTH_EXPIRED = "AUTH.TOKEN_EXPIRED"
    AUTH_REFRESH_INVALID = "AUTH.REFRESH_INVALID"
    AUTH_REFRESH_REUSED = "AUTH.REFRESH_REUSED"
    AUTH_WS_TICKET_INVALID = "AUTH.WS_TICKET_INVALID"
    FORBIDDEN = "AUTHZ.FORBIDDEN"
    ORG_NOT_FOUND = "ORG.NOT_FOUND"
    USER_EXISTS = "USER.EXISTS"
    USER_NOT_FOUND = "USER.NOT_FOUND"
    LOGIN_FAILED = "AUTH.LOGIN_FAILED"
    SCENARIO_NOT_FOUND = "SCENARIO.NOT_FOUND"
    SIM_NOT_FOUND = "SIMULATION.NOT_FOUND"
    SIM_RUNNING = "SIMULATION.RUNNING"
    SIM_CONCURRENCY_LIMIT = "SIMULATION.CONCURRENCY_LIMIT"
    SIM_STATUS_INVALID = "SIMULATION.STATUS_INVALID"
    DETECTION_NOT_FOUND = "DETECTION.NOT_FOUND"
    ACTION_UNKNOWN = "ACTION.UNKNOWN"
    ACTION_NOT_ALLOWED = "ACTION.NOT_ALLOWED"
    ACTION_UNCONFIRMED = "ACTION.UNCONFIRMED"
    KNOWLEDGE_NOT_FOUND = "KNOWLEDGE.NOT_FOUND"
    MISSION_NOT_FOUND = "MISSION.NOT_FOUND"
    BILLING_INVALID_STATE = "BILLING.INVALID_STATE"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY.KEY_REQUIRED"
    RATE_LIMITED = "RATE_LIMIT.EXCEEDED"
    NOT_IMPLEMENTED = "GENERAL.NOT_IMPLEMENTED"


#: HTTP status per error code (RFC 9457 `status`).
_ERROR_STATUS: dict[ErrorCode, int] = {
    ErrorCode.VALIDATION: 422,
    ErrorCode.AUTH_MISSING: 401,
    ErrorCode.AUTH_INVALID: 401,
    ErrorCode.AUTH_EXPIRED: 401,
    ErrorCode.AUTH_REFRESH_INVALID: 401,
    ErrorCode.AUTH_REFRESH_REUSED: 401,
    ErrorCode.AUTH_WS_TICKET_INVALID: 401,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.ORG_NOT_FOUND: 404,
    ErrorCode.USER_EXISTS: 409,
    ErrorCode.USER_NOT_FOUND: 404,
    ErrorCode.LOGIN_FAILED: 401,
    ErrorCode.SCENARIO_NOT_FOUND: 404,
    ErrorCode.SIM_NOT_FOUND: 404,
    ErrorCode.SIM_RUNNING: 409,
    ErrorCode.SIM_CONCURRENCY_LIMIT: 429,
    ErrorCode.SIM_STATUS_INVALID: 409,
    ErrorCode.DETECTION_NOT_FOUND: 404,
    ErrorCode.ACTION_UNKNOWN: 404,
    ErrorCode.ACTION_NOT_ALLOWED: 403,
    ErrorCode.ACTION_UNCONFIRMED: 409,
    ErrorCode.KNOWLEDGE_NOT_FOUND: 404,
    ErrorCode.MISSION_NOT_FOUND: 404,
    ErrorCode.BILLING_INVALID_STATE: 409,
    ErrorCode.IDEMPOTENCY_KEY_REQUIRED: 400,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.NOT_IMPLEMENTED: 501,
}


def error_status(code: ErrorCode) -> int:
    return _ERROR_STATUS[code]
